"""Second revision

Revision ID: bac12d3cf324
Revises: e1116f5af0ea
Create Date: 2023-09-06 23:09:54.189644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac12d3cf324'
down_revision = 'e1116f5af0ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('professors',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('professor_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=127), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('class_year', sa.String(length=100), nullable=True),
    sa.Column('dept', sa.String(length=100), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.professor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('professorsbio',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.professor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professor_id')
    )
    op.create_table('professorsphoto',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.professor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professor_id')
    )
    op.create_table('studentsbio',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('studentskills',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('studentsphoto',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('studentsresume',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('resume', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('response', sa.PickleType(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'student_id', name='uni_app')
    )
    op.create_table('dynamicapps',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('jobsdepartment',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'dept_id')
    )
    op.drop_table('professor')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='student_pkey'),
    sa.UniqueConstraint('username', name='student_username_key')
    )
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='professor_pkey'),
    sa.UniqueConstraint('username', name='professor_username_key')
    )
    op.drop_table('jobsdepartment')
    op.drop_table('dynamicapps')
    op.drop_table('applications')
    op.drop_table('studentsresume')
    op.drop_table('studentsphoto')
    op.drop_table('studentskills')
    op.drop_table('studentsbio')
    op.drop_table('professorsphoto')
    op.drop_table('professorsbio')
    op.drop_table('jobs')
    op.drop_table('students')
    op.drop_table('professors')
    op.drop_table('departments')
    # ### end Alembic commands ###
